#define MAX_MESSAGES 10
#define MOISTURE_INTERVAL 30
#define TEMP_INTERVAL 120
#define PIR_INTERVAL 2

#define PIR_PROB_IDENTIFIER 1
#define PIR_TIMER_IDENTIFIER 0
#define TEMP_IDENTIFIER 3
#define MOISTURE_IDENTIFIER 2
#define BATTERY_IDENTIFIER 4

#define PIR_TASKTIME 15
#define MOISTURE_TASKTIME 5
#define TEMP_TASKTIME 10
#define IRRIGATION_TIME_GAP 5

#define HIGH 1
#define LOW 0
#define TRIG "67"
#define ECHO "68"
#define VELOCITY 0.034
#define HALF_DISTANCE 2

#define WATER_UP_MARK 5
#define WATER_LOW_MARK 7

#define MOTOR_PIN "45"
#define VALVE_1_PIN "66"
#define VALVE_2_PIN "69"
#define SWITCH_PIN "49"
