char *path_to_direction(char *);
char *path_to_value(char *);
int delay_us(float);
int battery_status();
int get_distance();
int get_input(char *);
int set_output(char *, int);
int get_flowrate_1();
int get_flowrate_2();
int get_moisture();
int is_it_day();
int is_available();
int get_temperature();
int switch_condition();
void turn_on_motor();
void turn_off_motor();
void turn_on_valve1();
void turn_off_valve1();
void turn_on_valve2();
void turn_off_valve2();